### ISSUE TITLE
logo for ColorBox library

### ISSUE THREAD

**Issue by hafizahmmed** [enricocid/ColorBox-library#7]
Hello,
Good Day, i make a logo icon for your project.Because there is no logo in your project. If you want to use this icon in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.

![colorbox-library-01](https://user-images.githubusercontent.com/38810169/39676108-8affcd72-5186-11e8-8ab8-8d7a7fab852a.jpg)

Thankyou.

**Comment by enricocid** [comment]
Thank You. Very cool. Really appreciated

**Comment by hafizahmmed** [comment]
if you need i give you source file...

**Comment by hafizahmmed** [comment]
all file here https://drive.google.com/open?id=1UUMJquPucq-1VxhvitwBPShIyKrCW-GC

**Comment by enricocid** [comment]
Thanks. I've also updated the bintray page. Many thanks :) 
https://bintray.com/enricod/colorbox/cbl
